[package]
name = "monopoly"
version = "0.1.0"
edition = "2021"

[dependencies]

rand = "0.8"
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy_egui = "0.30"
bevy_prototype_lyon = "0.6"
